import { productFeatures } from "@/constants/utils";

export interface Product {
  id: number;
  name: string;
  category: string;
  description: string;
  image: string;
  price: string;
  features: string[];
  type: string;
}

export const products: Product[] = [
  {
    id: 1,
    name: "Automatic Bandsaw Machine ABS-300",
    category: "Heavy Duty",
    description: "High-precision cutting with advanced automation features and digital control system",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    price: "Contact for Price",
    features: [productFeatures.automatic, productFeatures.heavyDuty, productFeatures.digitalControl],
    type: "automatic",
  },
  {
    id: 2,
    name: "Semi-Auto Production SBS-350",
    category: "Medium Duty",
    description: "Optimized for production environments with quick material handling",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.semiAutomatic, productFeatures.production, productFeatures.quickClamp],
    type: "semi-automatic",
  },
  {
    id: 3,
    name: "Hydraulic Heavy HBS-500",
    category: "Premium",
    description: "Heavy-duty hydraulic system for large material cutting",
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60",
    price: "Contact for Price",
    features: [productFeatures.hydraulic, productFeatures.heavyDuty, productFeatures.largeCapacity],
    type: "hydraulic",
  },
  {
    id: 4,
    name: "Manual Precision MBS-250",
    category: "Standard",
    description: "High-precision manual bandsaw for detailed cutting work",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    price: "Contact for Price",
    features: [productFeatures.manual, productFeatures.precision, productFeatures.compact],
    type: "manual",
  },
  {
    id: 5,
    name: "Automatic Smart ABS-400",
    category: "Heavy Duty",
    description: "Smart automation features with IoT connectivity",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.automatic, productFeatures.smartControl, productFeatures.iotReady],
    type: "automatic",
  },
  {
    id: 6,
    name: "Semi-Auto Angle Cut SBS-280",
    category: "Medium Duty",
    description: "Specialized for angle cutting with digital angle display",
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60",
    price: "Contact for Price",
    features: [productFeatures.semiAutomatic, productFeatures.angleCut, productFeatures.digitalDisplay],
    type: "semi-automatic",
  },
  {
    id: 7,
    name: "Hydraulic Premium HBS-450",
    category: "Premium",
    description: "Premium hydraulic system with advanced monitoring",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    price: "Contact for Price",
    features: [productFeatures.hydraulic, productFeatures.premium, productFeatures.monitoringSystem],
    type: "hydraulic",
  },
  {
    id: 8,
    name: "Automatic CNC ABS-600",
    category: "Heavy Duty",
    description: "Advanced CNC control with multi-axis operation",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.automatic, productFeatures.cncControl, productFeatures.advanced],
    type: "automatic",
  },
  {
    id: 9,
    name: "Manual Workshop MBS-180",
    category: "Standard",
    description: "Reliable manual bandsaw for workshop applications",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    price: "Contact for Price",
    features: [productFeatures.manual, productFeatures.workshop, productFeatures.basic],
    type: "manual",
  },
  {
    id: 10,
    name: "Semi-Auto Compact SBS-220",
    category: "Medium Duty",
    description: "Space-saving design with efficient cutting capabilities",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.semiAutomatic, productFeatures.compact, productFeatures.spaceSaving],
    type: "semi-automatic",
  },
  {
    id: 11,
    name: "Hydraulic Power HBS-600",
    category: "Premium",
    description: "Maximum power hydraulic system for heavy materials",
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60",
    price: "Contact for Price",
    features: [productFeatures.hydraulic, productFeatures.powerCut, productFeatures.heavyDuty],
    type: "hydraulic",
  },
  {
    id: 12,
    name: "Automatic CNC ABS-500",
    category: "Heavy Duty",
    description: "Advanced CNC control with multi-axis operation",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.automatic, productFeatures.cncControl, productFeatures.advanced],
    type: "automatic",
  },
  {
    id: 13,
    name: "Manual Precision MBS-200",
    category: "Standard",
    description: "High-precision manual bandsaw for detailed cutting work",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    price: "Contact for Price",
    features: [productFeatures.manual, productFeatures.precision, productFeatures.compact],
    type: "manual",
  },
  {
    id: 14,
    name: "Automatic Smart ABS-350",
    category: "Heavy Duty",
    description: "Smart automation features with IoT connectivity",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.automatic, productFeatures.smartControl, productFeatures.iotReady],
    type: "automatic",
  },
  {
    id: 15,
    name: "Semi-Auto Production SBS-300",
    category: "Medium Duty",
    description: "Optimized for production environments with quick material handling",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.semiAutomatic, productFeatures.production, productFeatures.quickClamp],
    type: "semi-automatic",
  },
  {
    id: 16,
    name: "Hydraulic Heavy HBS-400",
    category: "Premium",
    description: "Heavy-duty hydraulic system for large material cutting",
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60",
    price: "Contact for Price",
    features: [productFeatures.hydraulic, productFeatures.heavyDuty, productFeatures.largeCapacity],
    type: "hydraulic",
  },
  {
    id: 17,
    name: "Manual Precision MBS-220",
    category: "Standard",
    description: "High-precision manual bandsaw for detailed cutting work",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    price: "Contact for Price",
    features: [productFeatures.manual, productFeatures.precision, productFeatures.compact],
    type: "manual",
  },
  {
    id: 18,
    name: "Automatic Smart ABS-300",
    category: "Heavy Duty",
    description: "Smart automation features with IoT connectivity",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.automatic, productFeatures.smartControl, productFeatures.iotReady],
    type: "automatic",
  },
  {
    id: 19,
    name: "Semi-Auto Production SBS-320",
    category: "Medium Duty",
    description: "Optimized for production environments with quick material handling",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.semiAutomatic, productFeatures.production, productFeatures.quickClamp],
    type: "semi-automatic",
  },
  {
    id: 20,
    name: "Hydraulic Heavy HBS-450",
    category: "Premium",
    description: "Heavy-duty hydraulic system for large material cutting",
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60",
    price: "Contact for Price",
    features: [productFeatures.hydraulic, productFeatures.heavyDuty, productFeatures.largeCapacity],
    type: "hydraulic",
  },
  {
    id: 21,
    name: "Manual Precision MBS-240",
    category: "Standard",
    description: "High-precision manual bandsaw for detailed cutting work",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    price: "Contact for Price",
    features: [productFeatures.manual, productFeatures.precision, productFeatures.compact],
    type: "manual",
  },
  {
    id: 22,
    name: "Automatic Smart ABS-320",
    category: "Heavy Duty",
    description: "Smart automation features with IoT connectivity",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.automatic, productFeatures.smartControl, productFeatures.iotReady],
    type: "automatic",
  },
  {
    id: 23,
    name: "Semi-Auto Production SBS-340",
    category: "Medium Duty",
    description: "Optimized for production environments with quick material handling",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.semiAutomatic, productFeatures.production, productFeatures.quickClamp],
    type: "semi-automatic",
  },
  {
    id: 24,
    name: "Hydraulic Heavy HBS-420",
    category: "Premium",
    description: "Heavy-duty hydraulic system for large material cutting",
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60",
    price: "Contact for Price",
    features: [productFeatures.hydraulic, productFeatures.heavyDuty, productFeatures.largeCapacity],
    type: "hydraulic",
  },
  {
    id: 25,
    name: "Automatic CNC ABS-600",
    category: "Heavy Duty",
    description: "Advanced CNC control with multi-axis operation",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.automatic, productFeatures.cncControl, productFeatures.advanced],
    type: "automatic",
  },
  {
    id: 26,
    name: "Manual Precision MBS-260",
    category: "Standard",
    description: "High-precision manual bandsaw for detailed cutting work",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    price: "Contact for Price",
    features: [productFeatures.manual, productFeatures.precision, productFeatures.compact],
    type: "manual",
  },
  {
    id: 27,
    name: "Automatic Smart ABS-340",
    category: "Heavy Duty",
    description: "Smart automation features with IoT connectivity",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.automatic, productFeatures.smartControl, productFeatures.iotReady],
    type: "automatic",
  },
  {
    id: 28,
    name: "Semi-Auto Production SBS-360",
    category: "Medium Duty",
    description: "Optimized for production environments with quick material handling",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.semiAutomatic, productFeatures.production, productFeatures.quickClamp],
    type: "semi-automatic",
  },
  {
    id: 29,
    name: "Hydraulic Heavy HBS-440",
    category: "Premium",
    description: "Heavy-duty hydraulic system for large material cutting",
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60",
    price: "Contact for Price",
    features: [productFeatures.hydraulic, productFeatures.heavyDuty, productFeatures.largeCapacity],
    type: "hydraulic",
  },
  {
    id: 30,
    name: "Manual Precision MBS-280",
    category: "Standard",
    description: "High-precision manual bandsaw for detailed cutting work",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    price: "Contact for Price",
    features: [productFeatures.manual, productFeatures.precision, productFeatures.compact],
    type: "manual",
  },
  {
    id: 31,
    name: "Automatic Smart ABS-360",
    category: "Heavy Duty",
    description: "Smart automation features with IoT connectivity",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.automatic, productFeatures.smartControl, productFeatures.iotReady],
    type: "automatic",
  },
  {
    id: 32,
    name: "Semi-Auto Production SBS-380",
    category: "Medium Duty",
    description: "Optimized for production environments with quick material handling",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.semiAutomatic, productFeatures.production, productFeatures.quickClamp],
    type: "semi-automatic",
  },
  {
    id: 33,
    name: "Hydraulic Heavy HBS-460",
    category: "Premium",
    description: "Heavy-duty hydraulic system for large material cutting",
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60",
    price: "Contact for Price",
    features: [productFeatures.hydraulic, productFeatures.heavyDuty, productFeatures.largeCapacity],
    type: "hydraulic",
  },
  {
    id: 34,
    name: "Manual Precision MBS-300",
    category: "Standard",
    description: "High-precision manual bandsaw for detailed cutting work",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    price: "Contact for Price",
    features: [productFeatures.manual, productFeatures.precision, productFeatures.compact],
    type: "manual",
  },
  {
    id: 35,
    name: "Automatic Smart ABS-380",
    category: "Heavy Duty",
    description: "Smart automation features with IoT connectivity",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.automatic, productFeatures.smartControl, productFeatures.iotReady],
    type: "automatic",
  },
  {
    id: 36,
    name: "Semi-Auto Production SBS-400",
    category: "Medium Duty",
    description: "Optimized for production environments with quick material handling",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.semiAutomatic, productFeatures.production, productFeatures.quickClamp],
    type: "semi-automatic",
  },
  {
    id: 37,
    name: "Hydraulic Heavy HBS-480",
    category: "Premium",
    description: "Heavy-duty hydraulic system for large material cutting",
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60",
    price: "Contact for Price",
    features: [productFeatures.hydraulic, productFeatures.heavyDuty, productFeatures.largeCapacity],
    type: "hydraulic",
  },
  {
    id: 38,
    name: "Manual Workshop MBS-180",
    category: "Standard",
    description: "Reliable manual bandsaw for workshop applications",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    price: "Contact for Price",
    features: [productFeatures.manual, productFeatures.workshop, productFeatures.basic],
    type: "manual",
  },
  {
    id: 39,
    name: "Semi-Auto Compact SBS-220",
    category: "Medium Duty",
    description: "Space-saving design with efficient cutting capabilities",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.semiAutomatic, productFeatures.compact, productFeatures.spaceSaving],
    type: "semi-automatic",
  },
  {
    id: 40,
    name: "Hydraulic Power HBS-600",
    category: "Premium",
    description: "Maximum power hydraulic system for heavy materials",
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60",
    price: "Contact for Price",
    features: [productFeatures.hydraulic, productFeatures.powerCut, productFeatures.heavyDuty],
    type: "hydraulic",
  },
  {
    id: 41,
    name: "Manual Precision MBS-320",
    category: "Standard",
    description: "High-precision manual bandsaw for detailed cutting work",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    price: "Contact for Price",
    features: [productFeatures.manual, productFeatures.precision, productFeatures.compact],
    type: "manual",
  },
  {
    id: 42,
    name: "Automatic Smart ABS-300",
    category: "Heavy Duty",
    description: "Smart automation features with IoT connectivity",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.automatic, productFeatures.smartControl, productFeatures.iotReady],
    type: "automatic",
  },
  {
    id: 43,
    name: "Semi-Auto Production SBS-420",
    category: "Medium Duty",
    description: "Optimized for production environments with quick material handling",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.semiAutomatic, productFeatures.production, productFeatures.quickClamp],
    type: "semi-automatic",
  },
  {
    id: 44,
    name: "Hydraulic Heavy HBS-400",
    category: "Premium",
    description: "Heavy-duty hydraulic system for large material cutting",
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60",
    price: "Contact for Price",
    features: [productFeatures.hydraulic, productFeatures.heavyDuty, productFeatures.largeCapacity],
    type: "hydraulic",
  },
  {
    id: 45,
    name: "Manual Precision MBS-340",
    category: "Standard",
    description: "High-precision manual bandsaw for detailed cutting work",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    price: "Contact for Price",
    features: [productFeatures.manual, productFeatures.precision, productFeatures.compact],
    type: "manual",
  },
  {
    id: 46,
    name: "Automatic Smart ABS-320",
    category: "Heavy Duty",
    description: "Smart automation features with IoT connectivity",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.automatic, productFeatures.smartControl, productFeatures.iotReady],
    type: "automatic",
  },
  {
    id: 47,
    name: "Semi-Auto Production SBS-440",
    category: "Medium Duty",
    description: "Optimized for production environments with quick material handling",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122",
    price: "Contact for Price",
    features: [productFeatures.semiAutomatic, productFeatures.production, productFeatures.quickClamp],
    type: "semi-automatic",
  },
  {
    id: 48,
    name: "Hydraulic Heavy HBS-420",
    category: "Premium",
    description: "Heavy-duty hydraulic system for large material cutting",
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60",
    price: "Contact for Price",
    features: [productFeatures.hydraulic, productFeatures.heavyDuty, productFeatures.largeCapacity],
    type: "hydraulic",
  },
  {
    id: 49,
    name: "Manual Precision MBS-360",
    category: "Standard",
    description: "High-precision manual bandsaw for detailed cutting work",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158",
    price: "Contact for Price",
    features: [productFeatures.manual, productFeatures.precision, productFeatures.compact],
    type: "manual",
  },
  {
    id: 50,
    name: "Hydraulic Master HBS-1000",
    category: "Premium",
    description: "Master-class hydraulic bandsaw with ultimate precision",
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60",
    price: "Contact for Price",
    features: [productFeatures.hydraulic, productFeatures.premium, productFeatures.ultimate],
    type: "hydraulic",
  }
];

